# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1f30b381ffd1e884b7b547d44e531d09"
name = "free-gifts"
handle = "free-gifts-8"
application_url = "https://record-going-reproduced-tooth.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-9757cb94.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://record-going-reproduced-tooth.trycloudflare.com/auth/callback",
  "https://record-going-reproduced-tooth.trycloudflare.com/auth/shopify/callback",
  "https://record-going-reproduced-tooth.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
